---
title: "Regions PHab Analysis"
author: "Leslie Jones"
date: "January 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(psych)
library(FactoMineR)
library(ade4)
library(amap)
library(vegan)
library(knitr)
library(reshape2)
library(MASS)
library(data.table)
library(factoextra)
library (colorspace)
library (RColorBrewer)
library(ggplot2)
library(lattice)
library(readr)
library (corrplot)
setwd ("C:/Habitat_Diversity/Analysis")

```

##Data management
```{r warning=FALSE results='hide'}
#load data
Phab <- read_csv("C:/Habitat_Diversity/Analysis/Data/Phab_HUClevel_NEW.csv")
#View(Phab)
Phab$cv_elev <- Phab$std_elev/Phab$avg_elev
Phab$cv_slope <- Phab$std_slope/Phab$avg_slope

#log transform skewed variables from 0. Corrlations in Phab Indicators
Phab$cv_elevT <- log(Phab$cv_elev +1)
Phab$area_glacT <- log(Phab$area_glac +1)
Phab$std_elevT <- log(Phab$std_elev + 1)
Phab$flood_stdareaT <- log(Phab$flood_stdarea + 1)
Phab$flood_densityT <- log(Phab$flood_density +1)
Phab$flood_TareaT <- log(Phab$flood_Tarea +1)
Phab$avg_l_elevT <- log(Phab$avg_l_elev +1)
Phab$std_l_areaT <- log(Phab$std_l_area +1)
Phab$area_lakesT <- log(Phab$area_lakes +1)
Phab$density_lakesT <- log(Phab$density_lakes +1)
Phab$density_glacT <- log(Phab$density_glac +1)
Phab$wetlandT <- log(Phab$wetland +1)
Phab$forestT <- log(Phab$forest +1)


#exclude character variables and redundant for PCA

exclude <- c("name", "region", "id_numeric", "n_mines", "density_mi", "hfp_std", "hfp09_std","region_id",
              "Pspr_90_15", "Pfall_90_15", "Pwin_90_15", "hfp09_max", "pike_stream_km", "pike_nlakes",
              "hfp09_mn", "area_mines",  "Psum_90_15", "max_lith_1", 
              "dem_max", "SK_length", "all_length", "CO_length", "CM_length", "SK_length", "ch_length", "PK_length", "forest",
             "slope_min", "dem_min", "chan_len", "slope_max", "std_l_area", "bare_HUC", "max_slope","max_elev",  "std_l_areaT",
             "std_elev",  "flood_density", "dem_std", "n_lakes", "flood_stdarea", "flood_stdareaT", "flood_denstiyT",
             "avg_l_elevT", "density_glac", "wetland", "area_glac", "area_lakes", "density_lakes", "forest", "cv_elev",
             
             "area_lakesT",  "Glacier_Density", "density_glacT", "Wetland", "wetlandT", "Forest", "forestT",
             "flood_densityT", "flood_Tarea", "Lake_area", "density_lakesT",
             
             "Std_Slope_Stream", "std_slope", "Std_Slope_HUC", "slope_std", "Std_Elevation_Stream", "std_elev",
             "Std_Elev_HUC", "elev_std", "CV_elev_Stream", "cv_elev", "tair_spawn90_15", "tair_grow90_15")
             


#rename vars
Phab3 <- rename(Phab, Glacier_Density = density_glacT, Avg_Elevation_HUC=dem_mean, Std_Slope_HUC=slope_std, 
                
               Avg_slope_HUC = slope_mean, Glacier_Area = area_glacT, Wetland = wetlandT,
               
               Channel_Complexity=nd_max, CV_elevation_HUC = dem_cv, Std_Elev_HUC = dem_std, Avg_slope_stream = avg_slope,
               
               River_Sinuosity = main_sinu, CV_Slope_Stream = cv_slope, 
               
               Avg_Elevation_Stream = avg_elev, Std_Elevation_Stream = std_elevT, 
               
               Floodplain_elev = flood_elev, Avg_lake_elev = avg_l_elev, Forest = forestT,
               
               Std_Slope_Stream = std_slope, CV_Slope_Stream = cv_slope, CV_elev_Stream = cv_elevT, 
               
               CV_Slope_HUC = slope_cv, Floodplain_Area = flood_TareaT, Shrub = shrub_HUC, Lake_area = area_lakesT,
               
               Density_lakes = density_lakesT)


#filter for regions based on too few HUCs - remove Aleutians, Arctic, Chignik, Kodiak, Prince William
#Phab3 <- Phab2 %>% filter(region %in% c("Bristol Bay", "Cook Inlet", "Chignik", "Copper River",
                                  #   "Kodiak", "Kuskokwim", "Southeast", "Prince William Sound")) 


apply(Phab3[,!names(Phab3) %in% exclude], 2, is.numeric)

Phabm <- Phab3[complete.cases(Phab3),] 
```

##PCA Analysis
Following methodology from: http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/
and http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/112-pca-principal-component-analysis-essentials/
```{r}

# need to scale and center data
Phab_z<-scale(Phabm[,!names(Phabm) %in% exclude], scale=TRUE, center=TRUE)

#compute PCA - all data
res.pca <- prcomp(Phab_z, scale = FALSE)

#vector arrows by phab
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)

#scree plot of eigenvalues - variance explained by each PC
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0,40))

#visualize the cos2 of variables
var <- get_pca_var(res.pca)
corrplot(var$cos2, is.corr = FALSE)

# Total cos2 of variables on Dim.1 and Dim.2
fviz_cos2(res.pca, choice = "var", axes = 1:2)

# Contributions of variables to PC1
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10)
# Contributions of variables to PC2
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10)
# Contributions of variables to PC3
fviz_contrib(res.pca, choice = "var", axes = 3, top = 10)


#pc1 is a tibble of all pc scores for 170 hucs.
pcscores <- as.tibble(scores(res.pca))
#View(pcscores)
#add huc and region to the pc scores.
pcout <- cbind(Phab3$region, Phab3$id_numeric, Phab3$region_id, pcscores)
#View(pcout)


#export csv with scores by huc and region
#write.csv(pcout, file="PCscores_huc_region.csv")


```

##PCA Plots
```{r}
#graph 
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)

#individuals by region
fviz_pca_ind(res.pca,
             col.ind = Phabm$region, # color by groups
             palette = ("rainbow_hcl"),
             addEllipses =FALSE,
             legend.title = "Groups",
             repel = TRUE
)

#individuals by region with ellipse
fviz_pca_ind(res.pca,
             col.ind = Phabm$region, # color by groups
             palette = ("rainbow_hcl"),
             addEllipses =TRUE,
             legend.title = "Groups",
             repel = TRUE
)
#pc 1 and 2 with points colored and shaped by region, ellipses around regions 
#habillage can be changed to display other factor variables - e.g. variable type.

fviz_pca_ind(res.pca, geom.ind = "point", axes = c(1,2), 
             repel = TRUE, habillage = Phabm$region, addEllipses = FALSE)

fviz_pca_ind(res.pca, geom.ind = "point", axes = c(1,2), 
             repel = TRUE, habillage = Phabm$region, addEllipses = TRUE)

fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE)


```

##Subset regions by salmon species
```{r}

```


#hucs and variables
```{r}


#F8766D
#B79F00
#00BA38
#00BFC4
#619CFF
#F564E3

#select ellipsoids
# Aleutian, Arctic only
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "white", "#F8766D", rep("white",11)))

#Aleutian, Arctic add Yukon
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "#B79F00", "#F8766D", rep("white",10), "#00BA38"))

#Aleutian, Arctic add Yukon add kuskokwim
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "#B79F00", "#F8766D", rep("white",6), "#00BFC4", rep("white",3), "#00BA38"))

#Aleutian, Arctic add Yukon add kuskokwim add kotzebue
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "#B79F00", "#F8766D", rep("white",5),"#619CFF", "#00BFC4", rep("white",3), "#00BA38"))

# Aleutian, Arctic add Yukon add kuskokwim add kotzebue
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "#B79F00", "#F8766D", rep("white",5),"#619CFF", "#00BFC4", rep("white",3), "#00BA38"))

# Aleutian, Arctic add Yukon add kuskokwim add kotzebue add Norton Sound
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "#B79F00", "#F8766D", rep("white",5),"#619CFF", "#00BFC4", "#F564E3", rep("white",2), "#00BA38"))

#other similar systems
# Cook Inlet and Bristol Bay copper and southest and PWS
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c( "mediumpurple1", "white", "#B79F00", "white", "#F8766D", "#619CFF", rep("white",4),
                             "yellow3", "#00BFC4", "white"))


#showing that Kodiak, chignik, and aleutian islands and PWS have too few pts to calculate ellipse
fviz_pca_biplot(res.pca, geom.ind = "point", axes = c(1,2), 
                repel = TRUE, habillage = Phabm$region, addEllipses = TRUE,
                palette = c(  "#B79F00",  rep("white",12)))







```


