---
title: "2. Climate PCA"
author: "Leslie Jones"
date: "January 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(psych)
library(FactoMineR)
library(ade4)
library(amap)
library(vegan)
library(knitr)
library(reshape2)
library(MASS)
library(data.table)
library(factoextra)
library (colorspace)
library (RColorBrewer)
library(ggplot2)
library(lattice)
library(readr)
library (corrplot)
setwd ("C:/Habitat_Diversity/Analysis")
```

## R Markdown

```{r}
#load data
Phab <- read_csv("C:/Habitat_Diversity/Analysis/Data/Phab_HUClevel_NEW.csv")
#View(Phab)
Phab$cv_elev <- Phab$std_elev/Phab$avg_elev
Phab$ cv_slope <- Phab$std_slope/Phab$avg_slope
#exclude character variables and redundant for PCA

exclude <- c("name", "region", "id_numeric", "n_mines", "density_mi", "hfp_std", "hfp09_std","region_id",
               "hfp09_max", "pike_stream_km", "pike_nlakes",
              "hfp09_mn", "area_mines",   "max_lith_1", 
              "dem_max", "slope_mean", "dem_mean", "slope_max", "area_glac", "wetland",
              "std_l_area", "bare_HUC", "avg_slope", "max_slope","max_elev", "std_elev",
             "SK_length", "all_length", "CO_length", "CM_length", "SK_length", "ch_length", "PK_length", "forest",
             "slope_min", "dem_min", "chan_len", "flood_stdarea", "flood_density", "dem_std", "n_lakes", "area_lakes",
             
             "density_glac", "dem_mean", "slope_std","nd_max", "dem_cv", "dem_std", "avg_slope",
               "main_sinu", "cv_slope", "wetland_HUC", "avg_elev", "std_elev", 
               "flood_elev", "avg_l_elev", "forest_HUC", "std_slope", "cv_slope", "cv_elev", 
               "slope_cv", "flood_Tarea", "shrub_HUC")

#"Pspr_90_15", "Pfall_90_15", "Pwin_90_15", "Psum_90_15", "tair_spawn90_15", "tair_grow90_15",
#rename vars
Phab3 <- rename(Phab, )


#filter for regions based on too few HUCs - remove Aleutians, Arctic, Chignik, Kodiak, Prince William
#Phab3 <- Phab2 %>% filter(region %in% c("Bristol Bay", "Cook Inlet", "Chignik", "Copper River",
                                  #   "Kodiak", "Kuskokwim", "Southeast", "Prince William Sound")) 


apply(Phab3[,!names(Phab3) %in% exclude], 2, is.numeric)

Phabm <- Phab3[complete.cases(Phab3),]
```

