---
title: "Model PC Scores"
author: "Leslie Jones"
date: "February 27, 2019"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, results='hide', message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(psych)
library(FactoMineR)
library(ade4)
library(amap)
library(vegan)
library(knitr)
library(reshape2)
library(MASS)
library(data.table)
library(factoextra)
library (colorspace)
library (RColorBrewer)
library(ggplot2)
library(lattice)
library(readr)
library (corrplot)
library(car)
library("PerformanceAnalytics")
setwd ("C:/Habitat_Diversity/Analysis")

```


##Model for Chinook

```{r}
#load data
pca <- read_csv("C:/Habitat_Diversity/Analysis/Data/pcscores_huc.csv")
chinook <- pca[complete.cases(pca$chinook_hab),]
View(chinook)

myvars <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub")
ch3 <- chinook[myvars] 
res <- cor(ch3)
round(res,2)
#write.csv(res, file="C:/Habitat_Diversity/Analysis/Data/corr_chinook.csv")

myvars2 <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub", "chinook_hab")
ch33 <- chinook[myvars2] 
chart.Correlation(ch33, histogram=TRUE, pch=19)

fit <- lm(chinook_hab ~ elev_avgW + wetland + ccomplexity + sinuosity + flood_elev + lake_elev  + elev_cvS + slope_avgS +  glacierA + floodplainA + lakeD + forest + shrub , data = chinook)

step <- stepAIC(fit, direction="both")
step$anova

summary (step)

# remove insignificant vars
fit2 <- lm(chinook_hab ~   sinuosity  + lake_elev  + elev_cvS + slope_avgS + forest + shrub, data = chinook)

summary (fit2)


vif(lm(chinook_hab ~  sinuosity  + lake_elev  + elev_cvS + slope_avgS + forest + shrub , data = chinook))


#predict on full dataframe
chinook_pred <- predict(fit2, pca)
chinook_out <- cbind(pca,chinook_pred) 
chinook_out$chin_pred2=(chinook_out$chinook_pred*100)
chinook_out$chin_hab2 = (chinook_out$chinook_hab*100)
View(chinook_out)

ggplot(chinook_out, aes(x=chinook_pred, y=chinook_hab)) + geom_point()


write.csv(chinook_out, file="C:/Habitat_Diversity/Analysis/Data/pred_chinook.csv")
```
##Model for Sockeye

```{r}
#load data
sock <- pca[complete.cases(pca$sockeye_hab),]

myvars <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub")
ch3s <- sock[myvars] 
ress <- cor(ch3s)
round(ress,2)
write.csv(ress, file="C:/Habitat_Diversity/Analysis/Data/corr_sock.csv")

myvars2 <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub", "sockeye_hab")
ch33s <- sock[myvars2] 
chart.Correlation(ch33s, histogram=TRUE, pch=19)

fits <- lm(sockeye_hab ~ elev_avgW + wetland + ccomplexity + sinuosity + flood_elev + lake_elev  + elev_cvS + slope_avgS +  glacierA + floodplainA + lakeD + forest + shrub , data = sock)


#fits <- lm(sockeye_hab ~ PC1 + PC2 , data = sock)
#summary(fits)


step2s <- stepAIC(fits, direction="both")
step2s$anova

summary (step2s)

fits2 <- lm(sockeye_hab ~ elev_avgW + wetland + ccomplexity  + elev_cvS + slope_avgS  + lakeD + forest + shrub , data = sock)

summary (fits2)

vif(lm(sockeye_hab ~ elev_avgW + wetland + ccomplexity  + elev_cvS + slope_avgS  + lakeD + forest + shrub, data = sock))


#predict on full dataframe
sock_pred <- predict(fits2, pca)
sock_out <- cbind(pca,sock_pred) 
sock_out$sock_pred2=(sock_out$sock_pred*100)
sock_out$sock_hab2 = (sock_out$sockeye_hab*100)
View(sock_out)

ggplot(sock_out, aes(x=sock_pred2, y=sock_hab2)) + geom_point()


write.csv(sock_out, file="C:/Habitat_Diversity/Analysis/Data/pred_sock.csv")
```

##Model for Chum

```{r}
#load data
chum <- pca[complete.cases(pca$chum_hab),]

myvars <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub")
ch3c <- chum[myvars] 
resc <- cor(ch3c)
round(resc,2)
write.csv(resc, file="C:/Habitat_Diversity/Analysis/Data/corr_chum.csv")

fitc <- lm(chum_hab ~ elev_avgW + wetland + ccomplexity + sinuosity + flood_elev + lake_elev  + elev_cvS + slope_avgS +  glacierA + floodplainA + lakeD + forest + shrub, data = chum)

step3c <- stepAIC(fitc, direction="both")
step3c$anova
summary (step3c)

fit2c <- lm(chum_hab ~ elev_avgW  + ccomplexity   + elev_cvS  + floodplainA  + forest + shrub, data = chum)

summary (fit2c)

vif(lm(chum_hab ~ elev_avgW  + ccomplexity   + elev_cvS  + floodplainA  + forest + shrub , data = chum))

#predict on full dataframe
chum_pred <- predict(fit2c, pca)
chum_out <- cbind(pca,chum_pred) 
chum_out$chum_pred2=(chum_out$chum_pred*100)
chum_out$chum_hab2 = (chum_out$chum_hab*100)
View(chum_out)

ggplot(chum_out, aes(x=chum_pred2, y=chum_hab2)) + geom_point()


write.csv(chum_out, file="C:/Habitat_Diversity/Analysis/Data/pred_chum.csv")
```

##Model for pink

```{r}
#load data
pink <- pca[complete.cases(pca$pink_hab),]

myvars <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub")
ch3p <- pink[myvars] 
resp <- cor(ch3p)
round(resp,2)
write.csv(resp, file="C:/Habitat_Diversity/Analysis/Data/corr_pink.csv")

fitp <- lm(pink_hab ~ elev_avgW + wetland + ccomplexity + sinuosity + flood_elev + lake_elev  + elev_cvS + slope_avgS +  glacierA + floodplainA + lakeD + forest + shrub, data = pink)

step4p <- stepAIC(fitp, direction="both")
step4p$anova
summary (step4p)

fit2p <- lm(pink_hab ~  wetland + ccomplexity  + elev_cvS  + forest + shrub, data = pink)

summary (fit2p)

vif(lm(pink_hab ~ wetland + ccomplexity  + elev_cvS  + forest + shrub , data = pink))

#predict on full dataframe
pink_pred <- predict(fit2p, pca)
pink_out <- cbind(pca,pink_pred) 
pink_out$pink_pred2=(pink_out$pink_pred*100)
pink_out$pink_hab2 = (pink_out$pink_hab*100)
View(pink_out)

ggplot(pink_out, aes(x=pink_pred2, y=pink_hab2)) + geom_point()


write.csv(pink_out, file="C:/Habitat_Diversity/Analysis/Data/pred_pink.csv")
```

##Model for coho

```{r}
#load data
coho <- pca[complete.cases(pca$coho_hab),]

myvars <- c("slope_avgW", "elev_avgW", "wetland", "ccomplexity", "sinuosity", "flood_elev", "lake_elev", "elev_avgS", "elev_cvS", "slope_avgS", "slope_cvS", "slope_cvW", "glacierA", "floodplainA", "lakeD", "forest", "shrub")
ch3o <- coho[myvars] 
reso <- cor(ch3o)
round(reso,2)
write.csv(reso, file="C:/Habitat_Diversity/Analysis/Data/corr_coho.csv")

fito <- lm(coho_hab ~ elev_avgW + wetland + ccomplexity + sinuosity + flood_elev + lake_elev  + elev_cvS + slope_avgS +  glacierA + floodplainA + lakeD + forest + shrub, data = coho)

step5o <- stepAIC(fito, direction="both")
step5o$anova
summary (step5o)

fit2o <- lm(coho_hab ~  wetland + ccomplexity  + flood_elev  +  glacierA  + forest + shrub, data = coho)

summary (fit2o)

vif(lm(coho_hab ~ wetland + ccomplexity  + flood_elev  +  glacierA  + forest + shrub , data = coho))


#predict on full dataframe
coho_pred <- predict(fit2o, pca)
coho_out <- cbind(pca,coho_pred) 
coho_out$coho_pred2=(coho_out$coho_pred*100)
coho_out$coho_hab2 = (coho_out$coho_hab*100)
View(coho_out)

ggplot(coho_out, aes(x=coho_pred2, y=coho_hab2)) + geom_point()


write.csv(coho_out, file="C:/Habitat_Diversity/Analysis/Data/pred_coho.csv")
```